const express = require('express');
const { getTasks, createTask, updateTask, deleteTask, getTasksPaginated, searchTasks, filterTasks } = require('../controllers/taskController');
const authMiddleware = require('../middleware/authMiddleware');
const router = express.Router();
router.get('/', authMiddleware, getTasks);
router.post('/', authMiddleware, createTask);
router.put('/:id', authMiddleware, updateTask);
router.delete('/:id', authMiddleware, deleteTask);
router.get('/paginated', authMiddleware, getTasksPaginated);
router.get('/search', authMiddleware, searchTasks);
router.get('/filter', authMiddleware, filterTasks);
module.exports = router;
